In [21]:
import numpy as np

class AR:
    def __init__(self, *phi, epsilon, Y0):
        self.phi = np.array(phi)
        self.epsilon = epsilon
        self.Y0 = np.array(Y0)
        self.memory = np.array([])
        self.YPast = np.array(self.Y0)

    def nPeriod(self, time):
        for i in range(time):
            self.epsilon(1)
            Y_one_step_ahead = self.phi@self.YPast + self.epsilon
            self.YPast = np.append(Y_one_step_ahead, self.YPast[:-1])
            self.memory = np.append(self.memory, Y_one_step_ahead)
            return  Y_one_step_ahead

In [22]:
import numpy as np

def Epsilon(mu, sigma):
    def draw(size):
        return np.random.normal(mu, sigma, size)
    return draw
    
epsilon = Epsilon(0, 0.4)

In [23]:
ar = AR(0.8, -0.35, epsilon=epsilon, Y0=[0,0])

print(ar.nPeriod(1))



TypeError: unsupported operand type(s) for +: 'float' and 'function'

In [24]:
import numpy as np
from numpy.linalg import inv
class Demand:
    def __init__(self, D, h):
        self.D=D
        self.h=h
    def quantity(self, pd):
        qd=np.array((self.D@pd)+self.h)
        return qd
class Supply:
    def __init__(self, C, e):
        self.C=C
        self.e=e
    def quantity(self, ps):
        qs=np.array((self.C@ps)+self.e)
        return qs 
class Market:
    def __init__(self, demand, supply):
        self.demand=demand
        self.supply=supply
    def price(self):
        pe=inv(self.supply.C-self.demand.D)@(self.demand.h-self.supply.e)
        return pe
    def quantity(self):
        qe=self.demand.D@self.price()+self.demand.h
        return qe
    def equilibrium(self):
        pe=self.price()
        qe=self.quantity()
        return pe, qe


D=np.array([
    [-10,-5],
    [-1,-10]
])
h=np.array([
    [100],
    [50]
])
C=np.array([
    [10,5],
    [5,10]
])
e=np.array([
    [0],
    [0]
])

demand = Demand(D, h)
supply = Supply(C, e)
market = Market(demand, supply)


market.equilibrium()

(array([[4.41176471],
        [1.17647059]]),
 array([[50.        ],
        [33.82352941]]))

In [25]:
# create supply shocks
import numpy as np
np.random.seed(2023)

epsilon = np.random.normal(0, 0.2, (10,2))

epsilon

array([[ 0.14233471, -0.06489699],
       [-0.20037413,  0.04725016],
       [-0.02043197, -0.22825853],
       [ 0.53088145,  0.28812104],
       [ 0.01978045, -0.62430643],
       [-0.21530433, -0.06513639],
       [-0.20709958, -0.08526408],
       [-0.20587228, -0.10435484],
       [-0.08455151, -0.01984883],
       [-0.2760516 ,  0.06038056]])